stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/

build-job:
  stage: build
  image: jeci/centos_deployer_gradle
  script:
    - gradle clean build
  tags:
    - docker

deploy-job:
  stage: deploy
  image: jeci/centos_deployer_gradle
  script:
    - "[ -z $ALF_HOST ] && exit 0"
    - gradle clean build
    - export ARTIFACT=`ls -1 build/libs/*.jar`
    - curl -v -X POST -F filedata=@$ARTIFACT -F siteid=$ALF_SITE -F containerid=documentLibrary -F uploaddirectory=/SAOD http://$ALF_USER:$ALF_PWD@$ALF_HOST/alfresco/service/api/upload
  tags:
    - docker
  only:
    - tags
