stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - curl -sS -u $CLD_USER:$CLD_PWD https://$CLD_HOST/remote.php/webdav/SAOD/ojdbc6.jar -o libs/ojdbc6.jar

cache:
  paths:
    - .gradle/

build-job:
  stage: build
  image: jeci/centos_deployer_gradle
  script:
    - gradle clean build
  tags:
    - docker

deploy-job:
  stage: deploy
  image: jeci/centos_deployer_gradle
  script:
    - "[ -z $CLD_HOST ] && exit 0"
    - gradle clean build
    - export ARTIFACT=`ls -1 build/libs/*.jar`
    - curl -sS -u $CLD_USER:$CLD_PWD -T $ARTIFACT https://$CLD_HOST/remote.php/webdav/SAOD/

  tags:
    - docker
  only:
    - tags
