version: "3.7"

services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  saod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        saod_version: 0.7.0
    image: jeci/saod
    volumes:
     - "./application-mysql.properties:/opt/saod/application.properties"
     - "./sqldb:/opt/saod/sqldb"
    command: ["java", "-jar", "jeci-saod-0.7.0.jar"]
    labels:
     - "traefik.frontend.rule=Host:saod.docker.localhost"

  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
